### ISSUE TITLE
Dangling reference to datasheet in interrupt example code

### ISSUE THREAD

**Issue by sonatique** [RobTillaart/PCF8574#10]
Reference to an unknown / unfound "figure 4 datasheet" in https://github.com/RobTillaart/PCF8574/blob/master/examples/PCF8574_interrupt/PCF8574_interrupt.ino but this is really minor of course.

**Comment by RobTillaart** [comment]
As this one was easy I copied a docs folder with the datasheet I use. 
No new release as there was no (meta) code change.
