### ISSUE TITLE
Support for Wire1/Wire2/Wire3/Wire4/Wire5

### ISSUE THREAD

**Issue by mattbue** [RobTillaart/PCF8574#14]
Hi, i have modified your code to support Wire1, Wire2, Wire3, Wire4 and Wire5 interfaces.
Are you interested on it for implementing into your code?

**Comment by RobTillaart** [comment]
Yes, please, if you can make a pull request I can review it.

For which platform do you use it? ( just tech curiosity )

**Comment by mattbue** [comment]
Great. Request is comming the next days.
Currently the my code runs on Teensy 4.1 using Wire2 interface.

**Comment by RobTillaart** [comment]
Please include the following
- [ ] update version in library.properties  -  0.2.5 or 0.3.0 )
- [ ] update version in library.json
- [ ] update version in .cpp and .h file 
- [ ] update the history in .cpp
- [ ] update the readme.md
- [ ] update license to include 2021 (Happy New Year!)
- [ ] ...

**Comment by mattbue** [comment]
I just created the pull request. But just included the .cpp and .h file.
Let me include the other stuff.

So I'm closing this issue.
