### ISSUE TITLE
Can't create multiple devices

### ISSUE THREAD

**Issue by LorenzoDelCerro** [RobTillaart/PCF8574#17]
When trying to call the constructor twice, for two PCF8574A devices with different addresses : 
![image](https://user-images.githubusercontent.com/49516101/111629563-b8123080-87f1-11eb-8feb-5277435a7691.png)
![image](https://user-images.githubusercontent.com/49516101/111629595-c1030200-87f1-11eb-893d-539ee01044a2.png)

I get the following error from the arduino compiler :

![image](https://user-images.githubusercontent.com/49516101/111629690-da0bb300-87f1-11eb-9e9a-8ce5b62efee5.png)

I couldn't find an example with two devices, so here I am !

Edit : My bad, I found an example in test1 but it still doesnt explain the error...

**Comment by LorenzoDelCerro** [comment]
My bad, somehow the library manager duplicated the file, thus the dual include... Sorry for being a moron and not seing this earlier !

**Comment by RobTillaart** [comment]
No problem, happens to all of use some day
