### ISSUE TITLE
work with tm1637

### ISSUE THREAD

**Issue by alirezaimi** [RobTillaart/PCF8574#18]
Hi
I use xreef library and can't work with tm1637 7segment module, 
Is there any luck in using this lib ?

**Comment by RobTillaart** [comment]
Hi,
I don't know the xreef library so I cannot comment on it.

> Is there any luck in using this lib ?

There are many different modules, so just give it a try as that is the real proof it works with your module and code.

**Comment by RobTillaart** [comment]
But be aware the PCF8574 is a complete other chip than the TM1637.
So do not expect it too work.... 
(but then again I do not know anything about your HW setup, code etc)

**Comment by RobTillaart** [comment]
I have a draft TM1637 lib that is not tested well enough or published yet. 
Can setup the repo as experimental...
