### ISSUE TITLE
PinMode missing

### ISSUE THREAD

**Issue by kishorasm123** [RobTillaart/PCF8574#37]
Hi Unable to set pin mode for all the pins in PC8574 using esp8266.
Earlier pins were idetified as P0,P1..... Now it's not there.
Can you please create a sample on how to set pin mode?

**Comment by RobTillaart** [comment]
Thanks for the issue. 
How did you solve it? (asking for future reference)

**Comment by kishorasm123** [comment]
Hi. I removed the setting PINMODE for the pcf8574. it worked. now it seems its not necessary set.

**Comment by RobTillaart** [comment]
thanks
