### ISSUE TITLE
README doesn't mention interrupt feature

### ISSUE THREAD

**Issue by thijstriemstra** [RobTillaart/PCF8574#40]
I found out by checking the examples.

**Comment by RobTillaart** [comment]
Thanks for the issue, I will add a section about it.
This might take some time.

**Comment by RobTillaart** [comment]
Added section in the readme - will create a new release asap/

**Comment by thijstriemstra** [comment]
awesome, thanks!

> The library does not support this internally.

was added to the readme, but I'm a little puzzled what it means (as opposed to.. externally..?) perhaps it could be clarified

**Comment by RobTillaart** [comment]
Ok, i understand the word internal does raise more questions so in some next release I will rephrase.

What I meant to say is that the library cannot handle the pcf8574 interrupts as it has no code for it. The user should catch it in his own code.

**Comment by RobTillaart** [comment]
New text is added to master branch, no new release for now.
