### ISSUE TITLE
PCF8574 Library Reverse() not found

### ISSUE THREAD

**Issue by souvikch** [RobTillaart/PCF8574#44]
Hello,
PCF8574 library reverse() is giving the following error in Arduino .
 error: 'class PCF8574' has no member named 'reverse'
   22 |   pcf.reverse();

 thanks
Souvik

**Comment by RobTillaart** [comment]
I will try to investigate today.

**Comment by souvikch** [comment]
Thankyou.. I've resolved the issue, there was some problem my header files.
But now I'm not able to use the reverse () function... do i need to call
the function everytime I call read or write.

Any help will be appreciated.

Regards

Souvik

**Comment by RobTillaart** [comment]
The purpose of the **reverse()** function is as a sort of animation, like **rotateLeft()**. It was not meant a a persistent reversing of the IO pins of the PCF8574 which is what I assume you are looking for.

**Comment by RobTillaart** [comment]
A solution might be using the **bitHelpers** library.
It has a stand alone **reverse()** function you can use.

**Comment by souvikch** [comment]
Thank you for your quick response and indeed I was trying the functionality
you mentioned.
I'll try bithelpers library as suggested by you.

Souvik Chakraborty

**Comment by RobTillaart** [comment]
As no more questions arise, I close the issue.
Feel free to reopen if not solved.
