### ISSUE TITLE
Documentation for readButton* functions 

### ISSUE THREAD

**Issue by sonatique** [RobTillaart/PCF8574#9]
Some explanation of benefits over read* functions and precisions regarding when to use them instead of read* and when not to use them instead of read* would be appreciated.

Background discussion here: https://github.com/RobTillaart/PCF8574/issues/6#issuecomment-744447162

**Comment by RobTillaart** [comment]
@sonatique 
Eons have passed but I finally added some explanation to the readme.md file about the **button** functions.
Also added a **getButtonMask()** to make the set functional complete.

See - https://github.com/RobTillaart/PCF8574/tree/develop

**Comment by sonatique** [comment]
Great, thanks a lot!

**Comment by RobTillaart** [comment]
Issue seems solved, so I close it.
